// Node and edge configuration for the neural network portfolio
// Each node has id, label, weight, skills, summary, projects, etc.

export const nodes = [
  {
    id: "jag",
    label: "Aaryan Patel",
    type: "central",
    weight: "strong",
    skills: ["AI/ML", "Cloud", "MLOps", "APIs", "Data Engineering"],
    summary: "Future Tech Entrepreneur with deep expertise in cloud, MLOps, and intelligent systems.",
    projects: ["AI Platform", "ML Monitoring", "Cloud Migration"],
  },
  {
    id: "aiml",
    label: "AI / ML",
    type: "skill",
    weight: "strong",
    skills: ["Deep Learning", "Agents", "NLP"],
    summary: "Machine learning, agents, and neural networks.",
    projects: ["Chatbot", "Vision System"],
  },
  {
    id: "mlops",
    label: "MLOps",
    type: "skill",
    weight: "strong",
    skills: ["CI/CD", "Monitoring", "Pipelines"],
    summary: "Production ML pipelines and monitoring.",
    projects: ["ML Monitoring", "CI/CD Automation"],
  },
  {
    id: "cloud",
    label: "Cloud Eng",
    type: "skill",
    weight: "strong",
    skills: ["Azure", "AWS", "Platform Engineering"],
    summary: "Cloud platforms and infrastructure.",
    projects: ["Cloud Migration", "Platform Engineering"],
  },
  {
    id: "llm",
    label: "LLM Eng",
    type: "skill",
    weight: "medium",
    skills: ["Prompt Design", "RAG", "Fine-tuning"],
    summary: "Large Language Models and prompt engineering.",
    projects: ["RAG System", "LLM Tuning"],
  },
  {
    id: "proj",
    label: "Projects",
    type: "skill",
    weight: "strong",
    skills: ["Real-world AI", "Cloud Systems"],
    summary: "AI and cloud project delivery.",
    projects: ["AI Platform", "Cloud Migration"],
  },
  {
    id: "certs",
    label: "Certs",
    type: "skill",
    weight: "medium",
    skills: ["Azure", "AWS", "Professional certs"],
    summary: "Professional certifications.",
    projects: ["Certification Pathways"],
  },
  {
    id: "edu",
    label: "Education",
    type: "skill",
    weight: "medium",
    skills: ["Academic", "Professional"],
    summary: "Academic and professional background.",
    projects: ["Degree", "Certifications"],
  },
  {
    id: "blog",
    label: "Blogs",
    type: "skill",
    weight: "learning",
    skills: ["Writing", "Tutorials", "Deep Dives"],
    summary: "Technical writing and tutorials.",
    projects: ["Blog Series"],
  },
  {
    id: "devsec",
    label: "DevSecOps",
    type: "skill",
    weight: "medium",
    skills: ["Security", "Compliance", "Zero Trust"],
    summary: "Security and compliance in DevOps.",
    projects: ["Security Automation"],
  },
  {
    id: "platform",
    label: "Platform",
    type: "skill",
    weight: "medium",
    skills: ["Self-hosted Infra", "Developer Portals"],
    summary: "Platform engineering and developer experience.",
    projects: ["Dev Portal"],
  },
  {
    id: "obs",
    label: "Observability",
    type: "skill",
    weight: "learning",
    skills: ["Logging", "Dashboards", "Alerting"],
    summary: "Observability and monitoring.",
    projects: ["Observability SDK"],
  },
  {
    id: "contact",
    label: "Contact",
    type: "skill",
    weight: "learning",
    skills: ["Get in touch"],
    summary: "Contact information.",
    projects: [],
  },
  {
    id: "about",
    label: "About",
    type: "skill",
    weight: "learning",
    skills: ["Background", "Experience"],
    summary: "Background and experience.",
    projects: [],
  },
];

export const edges = [
  { source: "jag", target: "aiml" },
  { source: "jag", target: "mlops" },
  { source: "jag", target: "cloud" },
  { source: "jag", target: "llm" },
  { source: "aiml", target: "proj" },
  { source: "aiml", target: "blog" },
  { source: "mlops", target: "proj" },
  { source: "mlops", target: "certs" },
  { source: "cloud", target: "proj" },
  { source: "cloud", target: "edu" },
  { source: "llm", target: "blog" },
  { source: "llm", target: "certs" },
  { source: "proj", target: "devsec" },
  { source: "proj", target: "platform" },
  { source: "proj", target: "obs" },
  { source: "blog", target: "obs" },
  { source: "blog", target: "contact" },
  { source: "certs", target: "about" },
  { source: "certs", target: "contact" },
  { source: "edu", target: "about" },
  { source: "edu", target: "platform" },
];