// Node and edge configuration for the neural network portfolio
// Each node has id, label, weight, skills, summary, projects, etc.

export const nodes = [
  [
  {
    id: "jag",
    label: "Aaryan Patel",
    type: "central",
    weight: "strong",
    skills: ["Learning Coding", "Maths", "Curiosity", "Problem Solving"],
    summary: "Year 8 student who enjoys learning coding, solving problems, and exploring technology.",
    projects: ["School Projects", "Simple Coding Tasks"],
  },
  {
    id: "coding",
    label: "Coding",
    type: "skill",
    weight: "learning",
    skills: ["Basics", "Simple Programs"],
    summary: "Learning the basics of coding and how to create simple programs.",
    projects: ["Basic Programs"],
  },
  {
    id: "math",
    label: "Maths",
    type: "skill",
    weight: "strong",
    skills: ["Numbers", "Logic", "Problem Solving"],
    summary: "Enjoys maths and solving different types of problems.",
    projects: ["School Work"],
  },
  {
    id: "web",
    label: "Web Learning",
    type: "skill",
    weight: "learning",
    skills: ["HTML", "Simple Pages"],
    summary: "Learning how websites are made and creating simple web pages.",
    projects: ["Personal Website"],
  },
  {
    id: "projects",
    label: "Projects",
    type: "skill",
    weight: "learning",
    skills: ["Practice", "Small Tasks"],
    summary: "Working on small projects to practice and improve skills.",
    projects: ["Mini Projects"],
  },
  {
    id: "learning",
    label: "Learning",
    type: "skill",
    weight: "strong",
    skills: ["School", "Online Practice"],
    summary: "Focused on learning new things through school and online resources.",
    projects: [],
  },
  {
    id: "school",
    label: "School",
    type: "skill",
    weight: "strong",
    skills: ["Maths", "Science", "Technology"],
    summary: "Studying core subjects and building a strong foundation.",
    projects: ["Assignments"],
  },
  {
    id: "blog",
    label: "Blog",
    type: "skill",
    weight: "learning",
    skills: ["Writing"],
    summary: "Writing about what I learn and my experiences.",
    projects: ["Blog Posts"],
  },
  {
    id: "tools",
    label: "Tools",
    type: "skill",
    weight: "learning",
    skills: ["Computer", "Basic Software"],
    summary: "Using basic tools for learning and completing projects.",
    projects: [],
  },
  {
    id: "safety",
    label: "Online Safety",
    type: "skill",
    weight: "learning",
    skills: ["Safe Internet Use"],
    summary: "Learning how to stay safe online.",
    projects: [],
  },
  {
    id: "contact",
    label: "Contact",
    type: "skill",
    weight: "learning",
    skills: ["Connect"],
    summary: "Ways to get in touch.",
    projects: [],
  },
  {
    id: "about",
    label: "About",
    type: "skill",
    weight: "learning",
    skills: ["Interests", "Background"],
    summary: "About me and what I like to learn.",
    projects: [],
  }
]
];

export const edges = [
  { source: "jag", target: "aiml" },
  { source: "jag", target: "mlops" },
  { source: "jag", target: "cloud" },
  { source: "jag", target: "llm" },
  { source: "aiml", target: "proj" },
  { source: "aiml", target: "blog" },
  { source: "mlops", target: "proj" },
  { source: "mlops", target: "certs" },
  { source: "cloud", target: "proj" },
  { source: "cloud", target: "edu" },
  { source: "llm", target: "blog" },
  { source: "llm", target: "certs" },
  { source: "proj", target: "devsec" },
  { source: "proj", target: "platform" },
  { source: "proj", target: "obs" },
  { source: "blog", target: "obs" },
  { source: "blog", target: "contact" },
  { source: "certs", target: "about" },
  { source: "certs", target: "contact" },
  { source: "edu", target: "about" },
  { source: "edu", target: "platform" },
];
